
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x1b\xa0\xfd\x8b\xd8\xcfJ\xe9\xc0 HV\xaf\xe9jn'
    
_lr_action_items = {'AND':([2,7,8,11,12,13,14,18,22,23,25,27,28,29,30,32,33,34,35,],[10,-7,-8,-18,24,-17,-16,-15,-3,-4,-12,-20,-21,-22,-19,-6,-11,-13,-5,]),'LIVING_IN':([4,5,6,7,8,9,10,11,12,13,14,18,22,23,24,25,26,27,28,29,30,31,33,34,35,],[11,-9,-10,-7,-8,11,11,-18,11,-17,-16,-15,-3,-4,11,-12,11,-20,-21,11,-19,11,-11,-13,-5,]),'OF':([7,8,9,29,],[-7,-8,20,20,]),'WHO':([7,8,9,29,],[-7,-8,21,21,]),'NUMBER':([15,19,],[27,30,]),'OR':([7,8,11,12,13,14,18,22,23,25,27,28,29,30,33,34,35,],[-7,-8,-18,26,-17,-16,-15,-3,-4,-12,-20,-21,-22,-19,-11,-13,-5,]),'HAVING_FOLLOWER_LESS_THAN':([4,5,6,7,8,9,10,11,12,13,14,18,22,23,24,25,26,27,28,29,30,31,33,34,35,],[15,-9,-10,-7,-8,15,15,-18,15,-17,-16,-15,-3,-4,15,-12,15,-20,-21,15,-19,15,-11,-13,-5,]),'FOLLOWERS':([0,],[5,]),'FOLLOW':([4,5,6,7,8,9,10,11,12,13,14,18,21,22,23,24,25,26,27,28,29,30,31,33,34,35,],[17,-9,-10,-7,-8,17,17,-18,17,-17,-16,-15,17,-3,-4,17,-12,17,-20,-21,17,-19,17,-11,-13,-5,]),'MY_FOLLOWERS':([0,],[6,]),'HAVING_FOLLOWER_GREATER_THAN':([4,5,6,7,8,9,10,11,12,13,14,18,22,23,24,25,26,27,28,29,30,31,33,34,35,],[19,-9,-10,-7,-8,19,19,-18,19,-17,-16,-15,-3,-4,19,-12,19,-20,-21,19,-19,19,-11,-13,-5,]),'FRIENDS':([0,17,20,],[7,7,7,]),'MY_FRIENDS':([0,17,20,],[8,8,8,]),'$end':([1,3,7,8,11,12,13,14,16,18,22,23,25,27,28,29,30,33,34,35,],[-1,0,-7,-8,-18,-14,-17,-16,-2,-15,-3,-4,-12,-20,-21,-22,-19,-11,-13,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'specificCond':([4,9,10,12,24,26,29,31,],[12,12,12,12,12,12,12,12,]),'F':([0,17,],[1,28,]),'whoFollow':([4,9,10,12,21,24,26,29,31,],[13,13,13,13,32,13,13,13,13,]),'friendsWithCond':([0,17,],[2,2,]),'start':([0,],[3,]),'follower':([0,],[4,]),'cond':([4,9,10,12,24,26,29,31,],[16,22,23,25,33,34,22,35,]),'placeCond':([4,9,10,12,24,26,29,31,],[18,18,18,18,18,18,18,18,]),'followCond':([4,9,10,12,24,26,29,31,],[14,14,14,14,14,14,14,14,]),'friend':([0,17,20,],[9,29,31,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> F','start',1,'p_start','parser.py',11),
  ('start -> follower cond','start',2,'p_start','parser.py',12),
  ('F -> friend cond','F',2,'p_F','parser.py',16),
  ('F -> friendsWithCond AND cond','F',3,'p_F','parser.py',17),
  ('F -> friend OF friend cond','F',4,'p_F','parser.py',18),
  ('friendsWithCond -> friend WHO whoFollow','friendsWithCond',3,'p_friendsWithCond','parser.py',23),
  ('friend -> FRIENDS','friend',1,'p_friend','parser.py',27),
  ('friend -> MY_FRIENDS','friend',1,'p_friend','parser.py',28),
  ('follower -> FOLLOWERS','follower',1,'p_follower','parser.py',32),
  ('follower -> MY_FOLLOWERS','follower',1,'p_follower','parser.py',33),
  ('cond -> specificCond AND cond','cond',3,'p_cond','parser.py',37),
  ('cond -> specificCond cond','cond',2,'p_cond','parser.py',38),
  ('cond -> specificCond OR cond','cond',3,'p_cond','parser.py',39),
  ('cond -> specificCond','cond',1,'p_cond','parser.py',40),
  ('specificCond -> placeCond','specificCond',1,'p_specificCond','parser.py',45),
  ('specificCond -> followCond','specificCond',1,'p_specificCond','parser.py',46),
  ('specificCond -> whoFollow','specificCond',1,'p_specificCond','parser.py',47),
  ('placeCond -> LIVING_IN','placeCond',1,'p_placeCond','parser.py',52),
  ('followCond -> HAVING_FOLLOWER_GREATER_THAN NUMBER','followCond',2,'p_followCond','parser.py',56),
  ('followCond -> HAVING_FOLLOWER_LESS_THAN NUMBER','followCond',2,'p_followCond','parser.py',57),
  ('whoFollow -> FOLLOW F','whoFollow',2,'p_whoFollow','parser.py',62),
  ('whoFollow -> FOLLOW friend','whoFollow',2,'p_whoFollow','parser.py',63),
]
