
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '*s\x8c\xf1\xfb\t%\x85\xc5\xcd\x07g\x1d\xd3.\x8c'
    
_lr_action_items = {'AND':([12,14,19,21,22,24,25,26,27,41,43,47,51,53,57,],[-20,-12,38,-25,-24,-28,-26,-27,-23,-29,-30,-18,-19,-11,-10,]),'ENDENTITY':([1,2,12,14,15,16,19,21,22,23,24,25,26,27,28,29,33,34,37,39,40,41,43,47,51,53,57,59,62,63,64,65,66,67,68,69,70,71,72,73,],[12,14,-20,-12,-31,-32,-22,-25,-24,45,-28,-26,-27,-23,46,47,51,53,57,12,14,-29,-30,-18,-19,-11,-10,-21,74,75,76,77,78,79,80,81,47,51,53,57,]),'MY':([0,17,18,20,60,61,],[6,31,6,31,31,6,]),'WHO':([1,2,12,14,15,16,29,30,32,33,34,35,36,37,45,46,47,51,53,57,74,75,76,77,78,79,80,81,],[11,13,-20,-12,-31,-32,48,49,50,52,54,55,56,58,-17,-9,-18,-19,-11,-10,-14,-15,-13,-16,-8,-5,-7,-6,]),'FOLLOWERS':([0,6,17,18,20,31,60,61,],[8,16,8,8,42,16,42,42,]),'OF':([8,10,42,44,],[17,18,60,61,]),'LIVING_IN_PLACE':([11,13,38,48,49,50,52,54,55,56,58,],[25,25,25,25,25,25,25,25,25,25,25,]),'FOLLOW':([11,13,38,48,49,50,52,54,55,56,58,],[20,20,20,20,20,20,20,20,20,20,20,]),'HAVING_FOLLOWERS_GREATER_THAN_NUM':([11,13,38,48,49,50,52,54,55,56,58,],[26,26,26,26,26,26,26,26,26,26,26,]),'FRIENDS':([0,6,17,18,20,31,60,61,],[10,15,10,10,44,15,44,44,]),'HAVING_FOLLOWERS_LESS_THAN_NUM':([11,13,38,48,49,50,52,54,55,56,58,],[24,24,24,24,24,24,24,24,24,24,24,]),'$end':([3,4,5,7,9,12,14,45,46,47,51,53,57,74,75,76,77,78,79,80,81,],[-4,-1,0,-3,-2,-20,-12,-17,-9,-18,-19,-11,-10,-14,-15,-13,-16,-8,-5,-7,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'myFollowers':([0,17,18,20,60,61,],[1,1,1,39,39,39,]),'placeCond':([11,13,38,48,49,50,52,54,55,56,58,],[27,27,27,27,27,27,27,27,27,27,27,]),'myFriends':([0,17,18,20,60,61,],[2,2,2,40,40,40,]),'whoFollow':([11,13,38,48,49,50,52,54,55,56,58,],[21,21,21,21,21,21,21,21,21,21,21,]),'followersWithoutCond':([0,17,18,20,60,61,],[3,29,34,41,70,72,]),'friendsWithCond':([0,17,18,],[4,30,35,]),'start':([0,],[5,]),'cond':([11,13,38,48,49,50,52,54,55,56,58,],[23,28,59,62,63,64,65,66,67,68,69,]),'followersWithCond':([0,17,18,],[7,32,36,]),'specificCond':([11,13,38,48,49,50,52,54,55,56,58,],[19,19,19,19,19,19,19,19,19,19,19,]),'friendsWithoutCond':([0,17,18,20,60,61,],[9,33,37,43,71,73,]),'followCond':([11,13,38,48,49,50,52,54,55,56,58,],[22,22,22,22,22,22,22,22,22,22,22,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> friendsWithCond','start',1,'p_start','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',8),
  ('start -> friendsWithoutCond','start',1,'p_start','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',9),
  ('start -> followersWithCond','start',1,'p_start','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',10),
  ('start -> followersWithoutCond','start',1,'p_start','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',11),
  ('friendsWithCond -> FRIENDS OF friendsWithCond WHO cond ENDENTITY','friendsWithCond',6,'p_friendsWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',16),
  ('friendsWithCond -> FRIENDS OF friendsWithoutCond WHO cond ENDENTITY','friendsWithCond',6,'p_friendsWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',17),
  ('friendsWithCond -> FRIENDS OF followersWithCond WHO cond ENDENTITY','friendsWithCond',6,'p_friendsWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',18),
  ('friendsWithCond -> FRIENDS OF followersWithoutCond WHO cond ENDENTITY','friendsWithCond',6,'p_friendsWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',19),
  ('friendsWithCond -> myFriends WHO cond ENDENTITY','friendsWithCond',4,'p_friendsWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',20),
  ('friendsWithoutCond -> FRIENDS OF friendsWithoutCond ENDENTITY','friendsWithoutCond',4,'p_friendsWithoutCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',24),
  ('friendsWithoutCond -> FRIENDS OF followersWithoutCond ENDENTITY','friendsWithoutCond',4,'p_friendsWithoutCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',25),
  ('friendsWithoutCond -> myFriends ENDENTITY','friendsWithoutCond',2,'p_friendsWithoutCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',26),
  ('followersWithCond -> FOLLOWERS OF followersWithCond WHO cond ENDENTITY','followersWithCond',6,'p_followersWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',30),
  ('followersWithCond -> FOLLOWERS OF followersWithoutCond WHO cond ENDENTITY','followersWithCond',6,'p_followersWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',31),
  ('followersWithCond -> FOLLOWERS OF friendsWithCond WHO cond ENDENTITY','followersWithCond',6,'p_followersWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',32),
  ('followersWithCond -> FOLLOWERS OF friendsWithoutCond WHO cond ENDENTITY','followersWithCond',6,'p_followersWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',33),
  ('followersWithCond -> myFollowers WHO cond ENDENTITY','followersWithCond',4,'p_followersWithCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',34),
  ('followersWithoutCond -> FOLLOWERS OF followersWithoutCond ENDENTITY','followersWithoutCond',4,'p_followersWithoutCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',38),
  ('followersWithoutCond -> FOLLOWERS OF friendsWithoutCond ENDENTITY','followersWithoutCond',4,'p_followersWithoutCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',39),
  ('followersWithoutCond -> myFollowers ENDENTITY','followersWithoutCond',2,'p_followersWithoutCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',40),
  ('cond -> specificCond AND cond','cond',3,'p_cond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',44),
  ('cond -> specificCond','cond',1,'p_cond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',45),
  ('specificCond -> placeCond','specificCond',1,'p_specificCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',50),
  ('specificCond -> followCond','specificCond',1,'p_specificCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',51),
  ('specificCond -> whoFollow','specificCond',1,'p_specificCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',52),
  ('placeCond -> LIVING_IN_PLACE','placeCond',1,'p_placeCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',57),
  ('followCond -> HAVING_FOLLOWERS_GREATER_THAN_NUM','followCond',1,'p_followCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',61),
  ('followCond -> HAVING_FOLLOWERS_LESS_THAN_NUM','followCond',1,'p_followCond','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',62),
  ('whoFollow -> FOLLOW followersWithoutCond','whoFollow',2,'p_whoFollow','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',67),
  ('whoFollow -> FOLLOW friendsWithoutCond','whoFollow',2,'p_whoFollow','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',68),
  ('myFriends -> MY FRIENDS','myFriends',2,'p_myFriends','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',72),
  ('myFollowers -> MY FOLLOWERS','myFollowers',2,'p_myFollowers','/Users/ayushchd/Sites/htdocs/djangodev/graphsearch/v2parser/parser.py',76),
]
